---
- name: Linux server configuration
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Display hostname
      debug:
        var: ansible_hostname

    - name: Display primary IP address
      debug:
        var: ansible_default_ipv4.address